In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('mlpract.csv')

In [3]:
dataset

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
dataset.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [6]:
x = dataset[['total_bill', 'tip' ,'sex', 'size']].values  #seprating independent variables

In [7]:
x          

array([[16.99, 1.01, 'Female', 2],
       [10.34, 1.66, 'Male', 3],
       [21.01, 3.5, 'Male', 3],
       [23.68, 3.31, 'Male', 2],
       [24.59, 3.61, 'Female', 4],
       [25.29, 4.71, 'Male', 4],
       [8.77, 2.0, 'Male', 2],
       [26.88, 3.12, 'Male', 4],
       [15.04, 1.96, 'Male', 2],
       [14.78, 3.23, 'Male', 2],
       [10.27, 1.71, 'Male', 2],
       [35.26, 5.0, 'Female', 4],
       [15.42, 1.57, 'Male', 2],
       [18.43, 3.0, 'Male', 4],
       [14.83, 3.02, 'Female', 2],
       [21.58, 3.92, 'Male', 2],
       [10.33, 1.67, 'Female', 3],
       [16.29, 3.71, 'Male', 3],
       [16.97, 3.5, 'Female', 3],
       [20.65, 3.35, 'Male', 3],
       [17.92, 4.08, 'Male', 2],
       [20.29, 2.75, 'Female', 2],
       [15.77, 2.23, 'Female', 2],
       [39.42, 7.58, 'Male', 4],
       [19.82, 3.18, 'Male', 2],
       [17.81, 2.34, 'Male', 4],
       [13.37, 2.0, 'Male', 2],
       [12.69, 2.0, 'Male', 2],
       [21.7, 4.3, 'Male', 2],
       [19.65, 3.0, 'Female', 2],
   

In [8]:
y = dataset[['smoker']].values

In [9]:
y

array([['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['No'],
    

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
imtr = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [12]:
impr = imtr.fit(x[:,0:7])

In [13]:
x = impr.transform(x[:,0:7])

In [14]:
x

array([[16.99, 1.01, 'Female', 2],
       [10.34, 1.66, 'Male', 3],
       [21.01, 3.5, 'Male', 3],
       [23.68, 3.31, 'Male', 2],
       [24.59, 3.61, 'Female', 4],
       [25.29, 4.71, 'Male', 4],
       [8.77, 2.0, 'Male', 2],
       [26.88, 3.12, 'Male', 4],
       [15.04, 1.96, 'Male', 2],
       [14.78, 3.23, 'Male', 2],
       [10.27, 1.71, 'Male', 2],
       [35.26, 5.0, 'Female', 4],
       [15.42, 1.57, 'Male', 2],
       [18.43, 3.0, 'Male', 4],
       [14.83, 3.02, 'Female', 2],
       [21.58, 3.92, 'Male', 2],
       [10.33, 1.67, 'Female', 3],
       [16.29, 3.71, 'Male', 3],
       [16.97, 3.5, 'Female', 3],
       [20.65, 3.35, 'Male', 3],
       [17.92, 4.08, 'Male', 2],
       [20.29, 2.75, 'Female', 2],
       [15.77, 2.23, 'Female', 2],
       [39.42, 7.58, 'Male', 4],
       [19.82, 3.18, 'Male', 2],
       [17.81, 2.34, 'Male', 4],
       [13.37, 2.0, 'Male', 2],
       [12.69, 2.0, 'Male', 2],
       [21.7, 4.3, 'Male', 2],
       [19.65, 3.0, 'Female', 2],
   

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_encoder = LabelEncoder()

In [17]:
x = label_encoder.fit_transform(x[:,2])

In [18]:
x

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
ohe = OneHotEncoder()

In [21]:
y = ohe.fit_transform(dataset.smoker.values.reshape(-1,1)).toarray()

In [22]:
y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.

In [23]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [60]:
x_train = x_train.reshape(-1, 1)

In [61]:
x_train

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [70]:
x_test = x_test.reshape(-1,1)

In [72]:
x_test

array([[1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0]])

In [81]:
y_train = y_train.reshape(-1,1)

In [82]:
y_train

array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],

In [83]:
y_test = y_test.reshape(-1,1)

In [84]:
y_test

array([[1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],

In [75]:
from sklearn.preprocessing import StandardScaler

In [76]:
sc_x = StandardScaler()

In [77]:
x_train = sc_x.fit_transform(x_train)

In [78]:
x_train

array([[ 0.68228824],
       [-1.46565622],
       [-1.46565622],
       [-1.46565622],
       [ 0.68228824],
       [-1.46565622],
       [-1.46565622],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [-1.46565622],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0.68228824],
       [ 0

In [79]:
x_test =sc_x.fit_transform(x_test)

In [80]:
x_test

array([[ 0.89714996],
       [ 0.89714996],
       [ 0.89714996],
       [-1.11464086],
       [-1.11464086],
       [-1.11464086],
       [ 0.89714996],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [ 0.89714996],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [-1.11464086],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [-1.11464086],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [ 0.89714996],
       [-1.11464086],
       [-1.11464086],
       [-1