In [1]:
import numpy as np  #importing liabraries

In [2]:
ary =  np.array([2,4,5,2])         #creating array by np.array([])

In [3]:
print(ary)

[2 4 5 2]


In [4]:
array = np.array([[1,2,3],[2,4,7],[8,6,9]])               #we can create matrix

In [5]:
array

array([[1, 2, 3],
       [2, 4, 7],
       [8, 6, 9]])

In [6]:
array.dtype           #shows data type

dtype('int32')

In [7]:
array.shape           #shows shape of array like 3 rows and 3 columns

(3, 3)

In [8]:
array.size            #gives numbers elements in array

9

In [15]:
array[0,1]=5            #can modify the element by - nameofarray[row, column] = value

In [16]:
array

array([[1, 5, 3],
       [2, 4, 7],
       [5, 5, 5]])

**methods that gives arrays of zeros**

In [17]:
zeroes  = np.zeros((2,3))

In [18]:
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

**Range Method**

In [19]:
rng = np.arange(6)

In [20]:
rng


array([0, 1, 2, 3, 4, 5])

**Linear space method**

In [21]:
lnspace = np.linspace(1,10,5)   #it will make array of 5 elements between 1-10

In [22]:
lnspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# some other methods

In [23]:
ar = np.arange(50)    #give numbers

In [24]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [25]:
a = ar.reshape(5,10)   #reshape the array in the format [row, column]


In [49]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [50]:
ar.ravel()   ##make 1-D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [30]:
ar.shape                #index of arrays starts from o as always

(50,)

In [31]:
a.sum(axis=0)          #addition columnwise axis=0 refer to columns

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [33]:
a.sum(axis=1)          #additon row-wise axis=1 refer to rows

array([ 45, 145, 245, 345, 445])

In [36]:
p = np.array([[3,5,7],[8,6,7],[4,2,8]])       #arrat in matrix form

In [37]:
p

array([[3, 5, 7],
       [8, 6, 7],
       [4, 2, 8]])

In [39]:
p.T             #for Transpose

array([[3, 8, 4],
       [5, 6, 2],
       [7, 7, 8]])

In [45]:
for i in p.flat:            #can accces each item of array
    print(i)

3
5
7
8
6
7
4
2
8


In [47]:
p.ndim     #shows no of Dimensions

2

In [48]:
p.nbytes   #show no of bytes

36

In [58]:
o = np.array([4,57,8,34,9,3])

In [70]:
o.argmax()           #gives the index which has highest value

1

In [60]:
o.argmin()           #gives the index which has lowest value

5

In [63]:
o.argsort()               #sort by index

array([5, 0, 2, 4, 3, 1], dtype=int64)

In [65]:
array   #to display array just write name of array 

array([[1, 5, 3],
       [2, 4, 7],
       [5, 5, 5]])

In [66]:
p        

array([[3, 5, 7],
       [8, 6, 7],
       [4, 2, 8]])

In [67]:
array+p                   #arrays addition 

array([[ 4, 10, 10],
       [10, 10, 14],
       [ 9,  7, 13]])

In [68]:
p * array

array([[ 3, 25, 21],
       [16, 24, 49],
       [20, 10, 40]])

In [69]:
np.sqrt(p)                 #takes squareroot of the values

array([[1.73205081, 2.23606798, 2.64575131],
       [2.82842712, 2.44948974, 2.64575131],
       [2.        , 1.41421356, 2.82842712]])

In [71]:
p.sum()      #give sums of array

50

In [72]:
p.min()      #give minimum value

2

In [73]:
p.max()       #give maximum value

8

In [77]:
np.where(p > 7)        

(array([1, 2], dtype=int64), array([0, 2], dtype=int64))

In [78]:
p[1,0]=0           #array manipulation where p[row, column]

In [79]:
p

array([[3, 5, 7],
       [0, 6, 7],
       [4, 2, 8]])

In [91]:
np.nonzero(p)        #gives indexes of non-zero values

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 1, 2, 0, 1, 2], dtype=int64))

In [93]:
np.count_nonzero(p)  #counts the non-zero numbers

8

In [94]:
p.itemsize

4

In [95]:
p.size

9

In [99]:
p.itemsize * p.size    #it takes less memory to store datas

36

In [102]:
p.tolist()      #convesrts it to list

[[3, 5, 7], [0, 6, 7], [4, 2, 8]]

In [103]:
import pandas as pd
#For more methods or attributes go to numpy